function E = energy_leg(in1,in2)
%ENERGY_LEG
%    E = ENERGY_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    08-Oct-2021 00:56:46

I1 = in2(5,:);
I2 = in2(6,:);
I3 = in2(7,:);
I4 = in2(8,:);
dth1 = in1(3,:);
dth2 = in1(4,:);
g = in2(19,:);
l_AC = in2(17,:);
l_A_m3 = in2(13,:);
l_B_m2 = in2(12,:);
l_C_m4 = in2(14,:);
l_OA = in2(15,:);
l_OB = in2(16,:);
l_O_m1 = in2(11,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
m4 = in2(4,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = dth1+dth2;
t5 = th1+th2;
t6 = dth1.^2;
t7 = l_O_m1.^2;
t8 = l_C_m4.*t2;
t9 = l_OA.*t2;
t10 = l_OB.*t2;
t11 = cos(t5);
t12 = l_OA.*t3;
t13 = sin(t5);
t14 = t4.^2;
t15 = l_AC.*t11;
t16 = l_A_m3.*t11;
t17 = l_B_m2.*t11;
t18 = t9+t16;
t19 = t10+t17;
t20 = t8+t9+t15;
E = (I1.*t6)./2.0+(I4.*t6)./2.0+(I2.*t14)./2.0+(I3.*t14)./2.0+(m4.*((dth2.*t15+dth1.*t20).^2.*2.0+(dth1.*(t12+l_AC.*t13+l_C_m4.*t3)+dth2.*l_AC.*t13).^2))./2.0+(m1.*(t2.^2.*t6.*t7.*2.0+t3.^2.*t6.*t7))./2.0+(m2.*((dth1.*(l_B_m2.*t13+l_OB.*t3)+dth2.*l_B_m2.*t13).^2+(dth2.*t17+dth1.*t19).^2.*2.0))./2.0+(m3.*((dth2.*t16+dth1.*t18).^2.*2.0+(dth1.*(t12+l_A_m3.*t13)+dth2.*l_A_m3.*t13).^2))./2.0-g.*m2.*t19-g.*m3.*t18-g.*m4.*t20-g.*l_O_m1.*m1.*t2;
