function rE = position_foot(in1,in2)
%POSITION_FOOT
%    RE = POSITION_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    08-Oct-2021 00:56:46

l_AC = in2(17,:);
l_DE = in2(18,:);
l_OB = in2(16,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = l_DE.*t3;
t6 = l_OB.*t3;
t7 = sin(t4);
t8 = l_AC.*t7;
t9 = t5+t6+t8;
rE = [t9;-l_DE.*t2-l_OB.*t2-l_AC.*cos(t4);t9];
