function drE = velocity_foot(in1,in2)
%VELOCITY_FOOT
%    DRE = VELOCITY_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    08-Oct-2021 00:56:46

dth1 = in1(3,:);
dth2 = in1(4,:);
l_AC = in2(17,:);
l_DE = in2(18,:);
l_OB = in2(16,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = l_DE.*t2;
t6 = l_OB.*t2;
t7 = cos(t4);
t8 = sin(t4);
t9 = l_AC.*t7;
t10 = dth2.*t9;
t11 = t5+t6+t9;
t12 = dth1.*t11;
t13 = t10+t12;
drE = [t13;dth1.*(l_AC.*t8+l_DE.*t3+l_OB.*t3)+dth2.*l_AC.*t8;t13];
