function keypoints = keypoints_bounding_leg(in1,in2)
%KEYPOINTS_BOUNDING_LEG
%    KEYPOINTS = KEYPOINTS_BOUNDING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    19-Nov-2021 00:33:52

l_AC = in2(20,:);
l_DE = in2(21,:);
l_EF = in2(22,:);
l_OA = in2(18,:);
l_OB = in2(19,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
x = in1(4,:);
y = in1(5,:);
t2 = sin(th1);
t3 = l_OA.*t2;
t4 = th1+th2;
t5 = sin(t4);
t6 = l_AC.*t5;
t7 = l_OB.*t2;
t8 = l_DE.*t2;
t9 = cos(th1);
t10 = cos(t4);
t11 = th1+th2+th3;
keypoints = reshape([x,y,t3,-l_OA.*t9,t7,-l_OB.*t9,t3+t6,-l_AC.*t10-l_OA.*t9,t6+t7,-l_AC.*t10-l_OB.*t9,t6+t7+t8,-l_AC.*t10-l_DE.*t9-l_OB.*t9,t6+t7+t8+l_EF.*sin(t11),-l_AC.*t10-l_DE.*t9-l_OB.*t9-l_EF.*cos(t11)],[2,7]);
