function rF = position_foot_rF(in1,in2)
%POSITION_FOOT_RF
%    RF = POSITION_FOOT_RF(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    19-Nov-2021 00:33:50

l_AC = in2(20,:);
l_DE = in2(21,:);
l_EF = in2(22,:);
l_OB = in2(19,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = sin(th1);
t3 = th1+th2;
t4 = cos(th1);
t5 = th1+th2+th3;
rF = [l_DE.*t2+l_OB.*t2+l_AC.*sin(t3)+l_EF.*sin(t5);-l_DE.*t4-l_OB.*t4-l_AC.*cos(t3)-l_EF.*cos(t5)];
