function Corr_Joint_Sp = Corr_leg(in1,in2)
%CORR_LEG
%    CORR_JOINT_SP = CORR_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    10-Nov-2021 14:56:16

dth1 = in1(4,:);
dth2 = in1(5,:);
dth3 = in1(6,:);
l_AC = in2(20,:);
l_A_m3 = in2(15,:);
l_B_m2 = in2(14,:);
l_C_m4 = in2(16,:);
l_DE = in2(21,:);
l_E_m5 = in2(17,:);
l_OA = in2(18,:);
l_OB = in2(19,:);
m2 = in2(2,:);
m3 = in2(3,:);
m4 = in2(4,:);
m5 = in2(5,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = sin(th2);
t3 = sin(th3);
t4 = th2+th3;
t5 = dth1.^2;
t6 = dth2.^2;
t7 = dth3.^2;
t8 = sin(t4);
t9 = l_AC.*l_E_m5.*m5.*t3.*t7;
t10 = dth1.*dth3.*l_AC.*l_E_m5.*m5.*t3.*2.0;
t11 = dth2.*dth3.*l_AC.*l_E_m5.*m5.*t3.*2.0;
t12 = -t10;
t13 = -t11;
t14 = -t9;
Corr_Joint_Sp = [t12+t13+t14-l_AC.*l_C_m4.*m4.*t2.*t6-l_AC.*l_DE.*m5.*t2.*t6-l_DE.*l_E_m5.*m5.*t6.*t8-l_DE.*l_E_m5.*m5.*t7.*t8-l_AC.*l_OA.*m4.*t2.*t6-l_AC.*l_OB.*m5.*t2.*t6-l_A_m3.*l_OA.*m3.*t2.*t6-l_B_m2.*l_OB.*m2.*t2.*t6-l_E_m5.*l_OB.*m5.*t6.*t8-l_E_m5.*l_OB.*m5.*t7.*t8-dth1.*dth2.*l_AC.*l_C_m4.*m4.*t2.*2.0-dth1.*dth2.*l_AC.*l_DE.*m5.*t2.*2.0-dth1.*dth2.*l_DE.*l_E_m5.*m5.*t8.*2.0-dth1.*dth3.*l_DE.*l_E_m5.*m5.*t8.*2.0-dth2.*dth3.*l_DE.*l_E_m5.*m5.*t8.*2.0-dth1.*dth2.*l_AC.*l_OA.*m4.*t2.*2.0-dth1.*dth2.*l_AC.*l_OB.*m5.*t2.*2.0-dth1.*dth2.*l_A_m3.*l_OA.*m3.*t2.*2.0-dth1.*dth2.*l_B_m2.*l_OB.*m2.*t2.*2.0-dth1.*dth2.*l_E_m5.*l_OB.*m5.*t8.*2.0-dth1.*dth3.*l_E_m5.*l_OB.*m5.*t8.*2.0-dth2.*dth3.*l_E_m5.*l_OB.*m5.*t8.*2.0;t12+t13+t14+l_AC.*l_C_m4.*m4.*t2.*t5+l_AC.*l_DE.*m5.*t2.*t5+l_DE.*l_E_m5.*m5.*t5.*t8+l_AC.*l_OA.*m4.*t2.*t5+l_AC.*l_OB.*m5.*t2.*t5+l_A_m3.*l_OA.*m3.*t2.*t5+l_B_m2.*l_OB.*m2.*t2.*t5+l_E_m5.*l_OB.*m5.*t5.*t8;l_E_m5.*m5.*(l_AC.*t3.*t5+l_AC.*t3.*t6+l_DE.*t5.*t8+l_OB.*t5.*t8+dth1.*dth2.*l_AC.*t3.*2.0)];
