function J = jacobian_foot(in1,in2)
%JACOBIAN_FOOT
%    J = JACOBIAN_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    03-Nov-2021 15:43:42

l_AC = in2(20,:);
l_DE = in2(21,:);
l_OB = in2(19,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = th1+th2;
t4 = cos(t3);
t5 = l_AC.*t4;
t6 = sin(th1);
t7 = sin(t3);
t8 = l_AC.*t7;
J = reshape([t5+l_DE.*t2+l_OB.*t2,t8+l_DE.*t6+l_OB.*t6,t5,t8],[2,2]);
