function dJ = jacobian_dot_foot(in1,in2)
%JACOBIAN_DOT_FOOT
%    DJ = JACOBIAN_DOT_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    03-Nov-2021 15:43:43

dth1 = in1(4,:);
dth2 = in1(5,:);
l_AC = in2(20,:);
l_DE = in2(21,:);
l_OB = in2(19,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = sin(th1);
t3 = th1+th2;
t4 = sin(t3);
t5 = cos(th1);
t6 = cos(t3);
t7 = dth2.*l_AC.*t6;
dJ = reshape([-dth1.*(l_AC.*t4+l_DE.*t2+l_OB.*t2)-dth2.*l_AC.*t4,t7+dth1.*(l_AC.*t6+l_DE.*t5+l_OB.*t5),-dth1.*l_AC.*t4-dth2.*l_AC.*t4,t7+dth1.*l_AC.*t6],[2,2]);
