function dJ_c = jacobian_dot_C(in1,in2)
%JACOBIAN_DOT_C
%    DJ_C = JACOBIAN_DOT_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    30-Nov-2021 01:30:17

dth1 = in1(6,:);
dth2 = in1(7,:);
l_AC = in2(20,:);
l_OA = in2(18,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = th1+th2;
t3 = sin(t2);
t4 = cos(t2);
t5 = dth2.*l_AC.*t4;
dJ_c = reshape([-dth1.*(l_AC.*t3+l_OA.*sin(th1))-dth2.*l_AC.*t3,t5+dth1.*(l_AC.*t4+l_OA.*cos(th1)),-dth1.*l_AC.*t3-dth2.*l_AC.*t3,t5+dth1.*l_AC.*t4,0.0,0.0,0.0,0.0,0.0,0.0],[2,5]);
