function dJ_a = jacobian_dot_A(in1,in2)
%JACOBIAN_DOT_A
%    DJ_A = JACOBIAN_DOT_A(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    30-Nov-2021 01:30:17

dth1 = in1(6,:);
l_OA = in2(18,:);
th1 = in1(1,:);
dJ_a = reshape([-dth1.*l_OA.*sin(th1),dth1.*l_OA.*cos(th1),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,5]);
