function dJ_e = jacobian_dot_E(in1,in2)
%JACOBIAN_DOT_E
%    DJ_E = JACOBIAN_DOT_E(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    30-Nov-2021 01:30:18

dth1 = in1(6,:);
dth2 = in1(7,:);
l_AC = in2(20,:);
l_DE = in2(21,:);
l_OB = in2(19,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = sin(th1);
t3 = th1+th2;
t4 = sin(t3);
t5 = cos(th1);
t6 = cos(t3);
t7 = dth2.*l_AC.*t6;
dJ_e = reshape([-dth1.*(l_AC.*t4+l_DE.*t2+l_OB.*t2)-dth2.*l_AC.*t4,t7+dth1.*(l_AC.*t6+l_DE.*t5+l_OB.*t5),-dth1.*l_AC.*t4-dth2.*l_AC.*t4,t7+dth1.*l_AC.*t6,0.0,0.0,0.0,0.0,0.0,0.0],[2,5]);
