function rO = position_rO(in1,in2)
%POSITION_RO
%    RO = POSITION_RO(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    30-Nov-2021 01:30:16

x = in1(4,:);
y = in1(5,:);
rO = [x;y];
