function drO = velocity_rO(in1,in2)
%VELOCITY_RO
%    DRO = VELOCITY_RO(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    30-Nov-2021 01:30:16

dx = in1(9,:);
dy = in1(10,:);
drO = [dx;dy];
