function drF = velocity_foot_rF(in1,in2)
%VELOCITY_FOOT_RF
%    DRF = VELOCITY_FOOT_RF(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    18-Nov-2021 12:00:58

dth1 = in1(6,:);
dth2 = in1(7,:);
dth3 = in1(8,:);
l_AC = in2(20,:);
l_DE = in2(21,:);
l_EF = in2(22,:);
l_OB = in2(19,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = l_AC.*t3;
t5 = cos(th1);
t6 = th1+th2+th3;
t7 = cos(t6);
t8 = l_EF.*t7;
t9 = sin(th1);
t10 = sin(t2);
t11 = l_AC.*t10;
t12 = sin(t6);
t13 = l_EF.*t12;
drF = [dth2.*(t4+t8)+dth1.*(t4+t8+l_DE.*t5+l_OB.*t5)+dth3.*l_EF.*t7;dth2.*(t11+t13)+dth1.*(t11+t13+l_DE.*t9+l_OB.*t9)+dth3.*l_EF.*t12];
