function J_d = jacobian_D(in1,in2)
%JACOBIAN_D
%    J_D = JACOBIAN_D(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    02-Dec-2021 00:21:59

l_AC = in2(20,:);
l_OB = in2(19,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = l_AC.*t3;
t5 = sin(t2);
t6 = l_AC.*t5;
J_d = reshape([t4+l_OB.*cos(th1),t6+l_OB.*sin(th1),t4,t6,0.0,0.0,1.0,0.0,0.0,1.0],[2,5]);
