function dJ_b = jacobian_dot_B(in1,in2)
%JACOBIAN_DOT_B
%    DJ_B = JACOBIAN_DOT_B(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    02-Dec-2021 00:21:58

dth1 = in1(6,:);
l_OB = in2(19,:);
th1 = in1(1,:);
dJ_b = reshape([-dth1.*l_OB.*sin(th1),dth1.*l_OB.*cos(th1),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,5]);
