function J_a = jacobian_A(in1,in2)
%JACOBIAN_A
%    J_A = JACOBIAN_A(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    02-Dec-2021 00:21:58

l_OA = in2(18,:);
th1 = in1(1,:);
J_a = reshape([l_OA.*cos(th1),l_OA.*sin(th1),0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0],[2,5]);
