function rO = position_rO(in1,in2)
%POSITION_RO
%    RO = POSITION_RO(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    02-Dec-2021 00:21:58

x = in1(4,:);
y = in1(5,:);
rO = [x;y];
