function rD = position_rD(in1,in2)
%POSITION_RD
%    RD = POSITION_RD(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    02-Dec-2021 00:21:57

l_AC = in2(20,:);
l_OB = in2(19,:);
th1 = in1(1,:);
th2 = in1(2,:);
x = in1(4,:);
y = in1(5,:);
t2 = th1+th2;
rD = [x+l_AC.*sin(t2)+l_OB.*sin(th1);y-l_AC.*cos(t2)-l_OB.*cos(th1)];
