function drC = velocity_rC(in1,in2)
%VELOCITY_RC
%    DRC = VELOCITY_RC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    02-Dec-2021 00:21:56

dth1 = in1(6,:);
dth2 = in1(7,:);
dx = in1(9,:);
dy = in1(10,:);
l_AC = in2(20,:);
l_OA = in2(18,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = sin(t2);
drC = [dx+dth1.*(l_AC.*t3+l_OA.*cos(th1))+dth2.*l_AC.*t3;dy+dth1.*(l_AC.*t4+l_OA.*sin(th1))+dth2.*l_AC.*t4];
