function C = C_jumping_leg(in1,in2,in3)
%C_JUMPING_LEG
%    C = C_JUMPING_LEG(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    19-Nov-2021 08:54:45

l_AC = in3(21,:);
l_DE = in3(22,:);
l_EF = in3(23,:);
l_OB = in3(20,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
y = in1(5,:);
t2 = cos(th1);
C = y-l_DE.*t2-l_OB.*t2-l_AC.*cos(th1+th2)-l_EF.*cos(th1+th2+th3);
