function dC = dC_jumping_leg(in1,in2,in3)
%DC_JUMPING_LEG
%    DC = DC_JUMPING_LEG(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    19-Nov-2021 08:54:46

dth1 = in1(6,:);
dth2 = in1(7,:);
dth3 = in1(8,:);
dy = in1(10,:);
l_AC = in3(21,:);
l_DE = in3(22,:);
l_EF = in3(23,:);
l_OB = in3(20,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = sin(th1);
t3 = th1+th2;
t4 = sin(t3);
t5 = l_AC.*t4;
t6 = th1+th2+th3;
t7 = sin(t6);
t8 = l_EF.*t7;
dC = dy+dth2.*(t5+t8)+dth1.*(t5+t8+l_DE.*t2+l_OB.*t2)+dth3.*l_EF.*t7;
