function E = energy_jumping_leg(in1,in2)
%ENERGY_JUMPING_LEG
%    E = ENERGY_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    17-Nov-2021 02:25:54

I1 = in2(9,:);
I2 = in2(10,:);
I3 = in2(11,:);
c1 = in2(2,:);
c2 = in2(3,:);
c3 = in2(4,:);
dth1 = in1(5,:);
dth2 = in1(6,:);
dy = in1(4,:);
g = in2(12,:);
l = in2(1,:);
m1 = in2(5,:);
m2 = in2(6,:);
m3 = in2(7,:);
mh = in2(8,:);
th1 = in1(2,:);
th2 = in1(3,:);
y = in1(1,:);
t2 = dth1.^2;
t5 = cos(th1);
t3 = dy+c1.*dth1.*t5;
t4 = sin(th1);
t6 = th1+th2;
t7 = cos(t6);
t13 = l.*t5.*2.0;
t8 = dy+dth1.*(t13+c3.*t7)+c3.*dth2.*t7;
t9 = sin(t6);
t10 = c3.*dth1.*t9+c3.*dth2.*t9;
t17 = c2.*t4;
t18 = l.*t4;
t11 = t17-t18;
t12 = dy+dth1.*(c2.*t5+l.*t5);
t14 = dy+dth1.*(t13+l.*t7)+dth2.*l.*t7;
t15 = dth1.*l.*t9+dth2.*l.*t9;
t16 = l.*t4.*2.0;
E = (I1.*t2)./2.0+(I2.*t2)./2.0+(I3.*t2)./2.0+(m1.*(t3.^2+c1.^2.*t2.*t4.^2))./2.0+(m2.*(t2.*t11.^2+t12.^2))./2.0+(m3.*(t8.^2+t10.^2))./2.0+(mh.*(t14.^2+t15.^2))./2.0+g.*m1.*(y+c1.*t4)+g.*m3.*(t16+y+c3.*t9)+g.*mh.*(t16+y+l.*t9)+g.*m2.*(t17+t18+y);
