function Grav_Joint_Sp = Grav_leg(in1,in2)
%GRAV_LEG
%    GRAV_JOINT_SP = GRAV_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    19-Nov-2021 08:54:46

g = in2(24,:);
kappa = in2(25,:);
l_AC = in2(21,:);
l_A_m3 = in2(16,:);
l_B_m2 = in2(15,:);
l_C_m4 = in2(17,:);
l_DE = in2(22,:);
l_E_m5 = in2(18,:);
l_OA = in2(19,:);
l_OB = in2(20,:);
l_O_m1 = in2(14,:);
m1 = in2(2,:);
m2 = in2(3,:);
m3 = in2(4,:);
m4 = in2(5,:);
m5 = in2(6,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th3_0 = in2(26,:);
t2 = sin(th1);
t3 = th1+th2;
t4 = sin(t3);
t5 = l_AC.*t4;
t6 = l_OA.*t2;
t7 = l_OB.*t2;
t8 = th1+th2+th3;
t9 = sin(t8);
t10 = l_E_m5.*t9;
Grav_Joint_Sp = [g.*m5.*(t5+t7+t10+l_DE.*t2)+g.*m3.*(t6+l_A_m3.*t4)+g.*m2.*(t7+l_B_m2.*t4)+g.*m4.*(t5+t6+l_C_m4.*t2)+g.*l_O_m1.*m1.*t2;g.*m5.*(t5+t10)+g.*l_AC.*m4.*t4+g.*l_A_m3.*m3.*t4+g.*l_B_m2.*m2.*t4;(kappa.*(th3.*2.0-th3_0.*2.0))./2.0+g.*l_E_m5.*m5.*t9;0.0;g.*(m2+m3+m4+m5)];
