function dJ = jacobian_dot_foot(in1,in2)
%JACOBIAN_DOT_FOOT
%    DJ = JACOBIAN_DOT_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    19-Nov-2021 08:51:41

dth1 = in1(6,:);
dth2 = in1(7,:);
dth3 = in1(8,:);
l_AC = in2(21,:);
l_DE = in2(22,:);
l_EF = in2(23,:);
l_OB = in2(20,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = sin(th1);
t3 = th1+th2;
t4 = sin(t3);
t5 = l_AC.*t4;
t6 = th1+th2+th3;
t7 = sin(t6);
t8 = l_EF.*t7;
t9 = t5+t8;
t10 = cos(t3);
t11 = l_AC.*t10;
t12 = cos(th1);
t13 = cos(t6);
t14 = l_EF.*t13;
t15 = t11+t14;
t16 = dth2.*t15;
t17 = dth3.*l_EF.*t13;
dJ = reshape([-dth2.*t9-dth1.*(t5+t8+l_DE.*t2+l_OB.*t2)-dth3.*l_EF.*t7,t16+t17+dth1.*(t11+t14+l_DE.*t12+l_OB.*t12),0.0,-dth1.*t9-dth2.*t9-dth3.*l_EF.*t7,t16+t17+dth1.*t15,0.0,-dth1.*l_EF.*t7-dth2.*l_EF.*t7-dth3.*l_EF.*t7,t17+dth1.*l_EF.*t13+dth2.*l_EF.*t13,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,5]);
