function keypoints = keypoints_jumping_leg(in1,in2)
%KEYPOINTS_JUMPING_LEG
%    KEYPOINTS = KEYPOINTS_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    17-Nov-2021 02:25:56

l = in2(1,:);
th1 = in1(2,:);
th2 = in1(3,:);
y = in1(1,:);
t2 = th1+th2;
t3 = sin(th1);
t4 = l.*t3.*2.0;
keypoints = reshape([-l.*cos(t2),t4+y+l.*sin(t2),0.0,0.0,t4+y,0.0,-l.*cos(th1),y+l.*t3,0.0,0.0,y,0.0],[3,4]);
