function J_f = jacobian_foot(in1,in2)
%JACOBIAN_FOOT
%    J_F = JACOBIAN_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-Nov-2021 13:56:43

l_AC = in2(20,:);
l_DE = in2(21,:);
l_EF = in2(22,:);
l_OB = in2(19,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = cos(t4);
t6 = sin(t4);
t7 = t4+th3;
t8 = cos(t7);
t9 = sin(t7);
t10 = l_AC.*t5;
t11 = l_AC.*t6;
t12 = l_EF.*t8;
t13 = l_EF.*t9;
J_f = reshape([t10+t12+l_DE.*t2+l_OB.*t2,t11+t13+l_DE.*t3+l_OB.*t3,t10+t12,t11+t13,t12,t13,1.0,0.0,0.0,1.0],[2,5]);
