function rF = position_foot_rF(in1,in2)
%POSITION_FOOT_RF
%    RF = POSITION_FOOT_RF(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-Nov-2021 13:56:42

l_AC = in2(20,:);
l_DE = in2(21,:);
l_EF = in2(22,:);
l_OB = in2(19,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
x = in1(4,:);
y = in1(5,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = t4+th3;
rF = [x+l_DE.*t3+l_OB.*t3+l_AC.*sin(t4)+l_EF.*sin(t5);y-l_DE.*t2-l_OB.*t2-l_AC.*cos(t4)-l_EF.*cos(t5)];
