function rB = position_rB(in1,in2)
%POSITION_RB
%    RB = POSITION_RB(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-Nov-2021 13:56:41

l_OB = in2(19,:);
th1 = in1(1,:);
x = in1(4,:);
y = in1(5,:);
rB = [x+l_OB.*sin(th1);y-l_OB.*cos(th1)];
