function drF = velocity_foot_rF(in1,in2)
%VELOCITY_FOOT_RF
%    DRF = VELOCITY_FOOT_RF(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-Nov-2021 13:56:42

dth1 = in1(6,:);
dth2 = in1(7,:);
dth3 = in1(8,:);
dx = in1(9,:);
dy = in1(10,:);
l_AC = in2(20,:);
l_DE = in2(21,:);
l_EF = in2(22,:);
l_OB = in2(19,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = cos(t4);
t6 = sin(t4);
t7 = t4+th3;
t8 = cos(t7);
t9 = sin(t7);
t10 = l_AC.*t5;
t11 = l_AC.*t6;
t12 = l_EF.*t8;
t13 = l_EF.*t9;
drF = [dx+dth2.*(t10+t12)+dth3.*t12+dth1.*(t10+t12+l_DE.*t2+l_OB.*t2);dy+dth2.*(t11+t13)+dth3.*t13+dth1.*(t11+t13+l_DE.*t3+l_OB.*t3)];
