function drO = velocity_rO(in1,in2)
%VELOCITY_RO
%    DRO = VELOCITY_RO(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-Nov-2021 13:56:42

dx = in1(9,:);
dy = in1(10,:);
drO = [dx;dy];
