function b = b_jumping_leg(in1,tau1,Fy,in4)
%B_JUMPING_LEG
%    B = B_JUMPING_LEG(IN1,TAU1,FY,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    16-Nov-2021 23:16:08

c1 = in4(2,:);
c2 = in4(3,:);
dth1 = in1(4,:);
dy = in1(3,:);
g = in4(9,:);
l = in4(1,:);
m1 = in4(4,:);
m2 = in4(5,:);
mh = in4(6,:);
th1 = in1(2,:);
t2 = sin(th1);
t3 = cos(th1);
t4 = c2.*t2;
t5 = l.*t2;
t6 = c2.*t3;
t7 = t4+t5;
t8 = l.*t3;
t9 = t6+t8;
t10 = dth1.*t9;
t11 = dy+t10;
t12 = t6-t8;
t13 = t4-t5;
t14 = c1.^2;
t15 = dth1.^2;
t16 = c1.*dth1.*t3;
t17 = dy+t16;
t18 = dth1.*l.*t3.*2.0;
t19 = dy+t18;
b = [Fy-g.*m1-g.*m2-g.*mh+dth1.*(dth1.*m2.*t7+c1.*dth1.*m1.*t2+dth1.*l.*mh.*t2.*2.0);tau1-(m1.*(c1.*dth1.*t2.*t17.*2.0-t2.*t3.*t14.*t15.*2.0))./2.0-(m2.*(dth1.*t7.*t11.*2.0-t12.*t13.*t15.*2.0))./2.0+dth1.*((m2.*(t7.*t11.*2.0+dth1.*t7.*t9.*2.0-dth1.*t12.*t13.*4.0))./2.0+(m1.*(c1.*t2.*t17.*2.0-dth1.*t2.*t3.*t14.*2.0))./2.0+l.*mh.*t2.*t19.*2.0+dth1.*l.^2.*mh.*t2.*t3.*4.0)-g.*m2.*t9-c1.*g.*m1.*t3-g.*l.*mh.*t3.*2.0-dth1.*l.*mh.*t2.*t19.*2.0];
