function C = C_jumping_leg(in1,tau1,in3)
%C_JUMPING_LEG
%    C = C_JUMPING_LEG(IN1,TAU1,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    16-Nov-2021 23:16:09

y = in1(1,:);
C = y;
