function dC = dC_jumping_leg(in1,tau1,in3)
%DC_JUMPING_LEG
%    DC = DC_JUMPING_LEG(IN1,TAU1,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    16-Nov-2021 23:16:09

dy = in1(3,:);
dC = dy;
